### ISSUE TITLE
Can't make your project /usr/bin/ld: cannot find -lp2p_lab_module

### ISSUE THREAD

**Issue by xiaosayin** [YuYen/mmsys23_gc#1]
/usr/bin/ld: cannot find -lp2p_lab_module

How can I install this lib in Ubuntu 20.04?

Look forward to your help.

Best regards!

**Comment by YuYen** [comment]
This work is build for mmsys 2023 grand challenge. The base framework source and documentation are available here: https://mmsysgc23.github.io/download/mmsys23-version-0.6-20230414.tar.gz

Your missing module can be found in from the package too. Then, put it into mpd/lib/debug.

Let me know if that help.
Thanks
